# -*- coding: utf-8 -*-
"""QRCodeGenerator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v10I-oQ4uPLds0vS8t6nPP9ybhZcq-8I
"""

pip install pyqrcode

pip install pypng

import pyqrcode 
import png 
from pyqrcode import QRCode 
  
  
# String which represents the QR code 
s = input("Enter your text/URL: ")
  
# Generate QR code 
url = pyqrcode.create(s) 
  
# Create and save the png file naming "myqr.png" 
url.png('myqr.png', scale = 6)